---
title: "Data"
author: "Gop Arop"
format: 
  html:
    embed-resources: true
    warning: false
editor_options: 
  chunk_output_type: console
---

-   Question of interest: How prominent has the 3 point shot been in the last 24 years? Also, how has it effected the top 20 players in each season?

```{r}
library(hoopR)
library(tidyverse)
library(rvest)
library(BasketballAnalyzeR)
```

## Shot Chart.
```{r}
shot_data <-  tibble(nba_shotchartdetail(league_id = '00', player_id = '2544', season = "2023-24"))

data <- shot_data[[1]][[1]] |> 
  mutate(LOC_X = as.numeric(LOC_X), LOC_Y = as.numeric(LOC_Y), xx = LOC_X/10, yy = LOC_Y/10 - 41.75) |> 
  rename(shot_distance = SHOT_DISTANCE, original_x = LOC_X, original_y = LOC_Y, converted_y = yy, converted_x = xx) |> 
  filter(EVENT_TYPE == "Made Shot")
```

```{r}
## Static Plot for LeBron James - 2023-24 Season

chart <- ggplot(data = data, aes(x = converted_x,y = converted_y)) + geom_point() + coord_fixed() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(fill = "white"), axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank())

drawNBAcourt(chart,full = TRUE)
```

```{r}
players <-  nba_leagueleaders(season = "2022-23", stat_category = "PTS", per_mode = "PerGame")

players <- players[["LeagueLeaders"]] |>
  mutate(PTS = as.numeric(PTS))

players <- players |>
  arrange(desc(PTS)) |>
  slice(1:20)

names(players)
```


## Quadrant Plot.
```{r}
library(plotly)
library(glue)
players <- players |> mutate(FG3A = as.numeric(FG3A), FGA = as.numeric(FGA)) |> mutate(image = sprintf("https://cdn.nba.com/headshots/nba/latest/260x190/%s.png", PLAYER_ID))
mean_y <- mean(players$FG3A)
mean_x <- mean(players$FGA)

quad_plot <- ggplot(players, aes(x=FGA, y=FG3A, label = PLAYER)) +
  geom_point() + 
  geom_image(aes(image = image), size = 0.09) +
  theme_minimal() +
  geom_vline(xintercept = mean_x) + geom_hline(yintercept = mean_y) 

quad_plot

ggplotly(quad_plot, tooltip = "label")
```

## Linear Model. 

```{r}
teams <- nba_teams()

team_stats <- nba_leaguedashteamstats(league_id = "00", season = "2023-24", team_id = "1610612737")

hawks_stats <- team_stats[[1]]
```

```{r}
team_ids <- teams |>
  distinct(team_id) |>
  pull(team_id)

seasons_choice <- paste0(substr(seq(2023, 2004), 1, 4), "-", substr(seq(2024, 2005), 3, 4)) |> as.factor()

```

```{r}
team_totals <- tibble()

for (year in 2000:2010) {
  Sys.sleep(4)
  
  teamStats_url <- sprintf("https://www.basketball-reference.com/leagues/NBA_%s.html", year)
  
  team_stats <- read_html(teamStats_url) |> 
    html_nodes("table") |>
    html_table() 
  
  team_stats_current <- team_stats[[6]]
  
  team_stats_current$SEASON <- year
  
  team_totals <- bind_rows(team_totals, team_stats_current) 
}

for (year in 2011:2015) {
  Sys.sleep(4)
  
  teamStats_url <- sprintf("https://www.basketball-reference.com/leagues/NBA_%s.html", year)
  
  team_stats <- read_html(teamStats_url) |> 
    html_nodes("table") |>
    html_table() 
  
  team_stats_current <- team_stats[[6]]
  
  team_stats_current$SEASON <- year
  
  team_totals <- bind_rows(team_totals, team_stats_current) 
}

for (year in 2016:2024) {
  Sys.sleep(4)
  
  teamStats_url <- sprintf("https://www.basketball-reference.com/leagues/NBA_%s.html", year)
  
  team_stats <- read_html(teamStats_url) |> 
    html_nodes("table") |>
    html_table() 
  
  team_stats_current <- team_stats[[8]]
  
  team_stats_current$SEASON <- year
  
  team_totals <- bind_rows(team_totals, team_stats_current) 
}


```

```{r}
team_totals <- team_totals |>
  mutate(SEASON = as.factor(SEASON)) |>
  filter(Team != "League Average")
```


```{r}
library(broom)
threepoint_mod <- lm(`3PA` ~ SEASON, data = team_totals)
summary(threepoint_mod)
```


